### ISSUE TITLE
Change mode

### ISSUE THREAD

**Issue by GlenHughes** [vardius/web-component#15]
It would be great if we could set the mode to closed. Looking at the code this doesn't seem possible as it's hardcoded to open: https://github.com/vardius/web-component/blob/4f125e4388eca88031660a8a7e4cc74bad566ee8/src/connectedCallback/index.js#L13

Will send a PR to make this possible to change via the options. :)

**Comment by vardius** [comment]
Thanks @GlenHughes ! happy to see some contributions !

**Comment by vardius** [comment]
Please find the following:
https://github.com/vardius/web-component/releases/tag/v1.0.26
https://www.npmjs.com/package/web-component/v/1.0.26

Please close issue if you find this to be resolved.
